from __future__ import annotations

import json
from pathlib import Path
from typing import Dict

import yaml

from .inspection import inspect_model


def emit_slime_plan(candidate: str | Path, out: str | Path) -> Dict[str, object]:
    candidate_path = Path(candidate).expanduser().resolve()
    out_dir = Path(out).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    spec = inspect_model(candidate_path)

    trainable_patterns = [
        ".*mlp\\.experts\\.(gate_up_proj|down_proj).*",
        ".*mlp\\.shared_expert\\.(gate_proj|up_proj|down_proj|gate_up_proj).*",
        ".*mlp\\.gate\\.weight.*",
    ]
    freeze_patterns = [
        ".*embed_tokens.*",
        ".*lm_head.*",
        ".*self_attn.*",
        ".*linear_attn.*",
        ".*norm.*",
        ".*vision.*",
    ]
    phases = {
        "candidate": str(candidate_path),
        "model_type": spec.model_type,
        "assumed_compute": "single 8xB300 288GB node",
        "phases": [
            {
                "name": "phase_0_no_train_verification",
                "goal": "Run ablx probe and short-context serving smoke tests before any training.",
                "gates": [
                    "no NaNs",
                    "perplexity delta <= 5-10%",
                    "source/candidate top-1 agreement >= 90%",
                    "stable activation and router telemetry",
                ],
            },
            {
                "name": "phase_1_distillation_warmup",
                "goal": "Train only new expert capacity plus optional router/shared expert parameters.",
                "losses": ["source-logit KL", "CE on curated continuation data", "router/load-balance diagnostics"],
                "trainable_patterns": trainable_patterns,
                "freeze_patterns": freeze_patterns,
            },
            {
                "name": "phase_2_continued_sft_pretraining",
                "goal": "Unfreeze inherited MoE weights at lower LR while keeping source KL active.",
                "notes": ["use domain slices for web/code/math/dialogue/multilingual", "log tokens-to-target-loss"],
            },
            {
                "name": "phase_3_slime_grpo_opd",
                "goal": "Use slime with Megatron training and SGLang rollouts for math/code/agent rewards.",
                "rollout_backend": "SGLang",
                "training_backend": "Megatron via slime",
            },
        ],
    }
    freeze_masks = {
        "trainable_patterns": trainable_patterns,
        "freeze_patterns": freeze_patterns,
        "slice_policy": "prefer new expert slices when the training stack supports slice masks; otherwise train full matched tensors at low LR",
    }
    commands = {
        "debug_rollout_only": "python train.py --debug-rollout-only <slime args>",
        "debug_train_only": "python train.py --debug-train-only <slime args>",
        "full_run": "python train.py <megatron args> <sglang args> <custom reward/data args>",
    }

    (out_dir / "slime_phases.yaml").write_text(yaml.safe_dump(phases, sort_keys=False), encoding="utf-8")
    (out_dir / "freeze_masks.yaml").write_text(yaml.safe_dump(freeze_masks, sort_keys=False), encoding="utf-8")
    (out_dir / "commands.json").write_text(json.dumps(commands, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (out_dir / "README.md").write_text(render_readme(candidate_path), encoding="utf-8")
    return {
        "out": str(out_dir),
        "files": ["slime_phases.yaml", "freeze_masks.yaml", "commands.json", "README.md"],
        "candidate": str(candidate_path),
    }


def render_readme(candidate: Path) -> str:
    return f"""# slime plan for {candidate.name}

This directory is generated by `ablx slime-plan`.

Run order:

1. Serve/load the candidate at short context and run `ablx probe`.
2. Run slime rollout-only and train-only debug modes.
3. Start phase 1 distillation with only new MoE capacity trainable.
4. Move to SFT/continued pretraining once preservation gates pass.
5. Run GRPO/OPD-style slime tuning with SGLang rollouts.

The emitted YAML files are templates. Keep the run manifest, dataset hashes,
prompt templates, slime commit, Megatron/SGLang versions, and checkpoint hashes
with every experiment.
"""
